#!/usr/bin/env ruby

require "optparse"

#  git-contrib.rb
#  Author: William Woodruff
#  ------------------------
#  Generates a CONTRIBUTORS file for a git repository
#  ------------------------
#  This program is licensed by William Woodruff under the MIT License.
#  http://opensource.org/licenses/MIT

system("git rev-parse 2>/dev/null") or abort("No git repository found. Exiting.")

options = {}

optparse = OptionParser.new do |opts|
	opts.banner = "Usage: git-contrib.rb [-m|-c]"

	options[:markdown] = false
	opts.on('-m', '--markdown', 'Use markdown formatting') do
		options[:markdown] = true
	end

	options[:csv] = false
	opts.on('-c', '--csv', 'Use csv formatting') do
		options[:csv] = true
	end

	opts.on('-h', '--help', 'Display this screen') do
    	puts opts
    	exit
   end
end

optparse.parse!

if options[:markdown]
	
elsif options[:csv]

else
	File.open("CONTRIBUTORS", "w") do |contribFile|
		contribFile.write("CONTRIBUTORS\n")
		contribFile.write("Generated by git-contrib on #{`date +"%H:%M:%S %Y/%m/%d"`}")
		contribFile.write("-------------------------------------------------\n\n")
		contribFile.write("Commits\tAuthor\n")

		contribFile.write(`git shortlog -s -n`)

		contribFile.write("\n")
	end
end



